export const lineArr=[
             {
                    x:400,
                    y:200,
                    width:12,
                    height:28,//28
                    fixHeight:7.5,
                    style:{
                      fill:'#7ACDFE',
                    },
                    weight:0.98,
              },
              {
                    x:430,
                    y:200,
                    width:12,
                    height:18,//18
                    fixHeight:6,
                    style:{
                      fill:'#71B7FD',
                    },
                    weight:0.68
             },
             {
                  x:460,
                    y:200,
                    width:12,
                    height:8,
                    fixHeight:4,//14
                    style:{
                      fill:'#68A3FD',
                    },
                    weight:0.36
             },
             {
                  x:490,
                    y:200,
                    width:12,
                    height:8,
                    fixHeight:2.25,//9
                    style:{
                      fill:'#608EFC',
                    },
                    weight:0.14,
             },
             {
                    x:370,
                    y:200,
                    width:12,
                    height:60,
                    fixHeight:9,//24
                    style:{
                      fill:'#82E1FF',
                    },
                    weight:1.42,
             },
             {
                  x:340,
                    y:200,
                    width:12,
                    height:28,
                    fixHeight:7.5,//28
                    style:{
                      fill:'#7ACDFE',
                    },
                    weight:0.98,
             },{
                  x:310,
                    y:200,
                    width:12,
                    height:18,
                    fixHeight:6,//18
                    style:{
                      fill:'#71B7FD',
                    },
                    weight:0.68,
             },
             {
                  x:280,
                    y:200,
                    width:12,
                    height:8,
                    fixHeight:4,
                    style:{
                      fill:'#68A3FD',
                    }, 
                    weight:.36,                 
             },
             {
                  x:250,
                    y:200,
                    width:12,
                    height:8, 
                    fixHeight:2.25,//9
                    style:{
                      fill:'#608EFC',
                    },
                    weight:0.14,
             }
]

export const circleArr=[
             {
             	x:220,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:190,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:160,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:130,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:520,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:550,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:580,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',
             	}
             },{
             	x:610,
             	y:200,
             	r:6,
             	startAngle:0,
             	endAngle:Math.PI * 2,
             	style:{
             		fill:'#597CFC',

             	}
             }
]

/**
 * export const lineArr=[
             {
                    x:400,
                    y:200,
                    width:12,
                    height:0,//28
                    fixHeight:5,
                    style:{
                      fill:'#7ACDFE',
                    },
                    weight:1,
              },{
                    x:430,
                    y:200,
                    width:12,
                    height:0,//18
                    fixHeight:5,
                    style:{
                      fill:'#71B7FD',
                    },
                    weight:0.9
             },{
                  x:460,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//14
                    style:{
                      fill:'#68A3FD',
                    },
                    weight:0.72
             },{
                  x:490,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//9
                    style:{
                      fill:'#608EFC',
                    },
                    weight:0.4,
             },{
                  x:370,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//24
                    style:{
                      fill:'#82E1FF',
                    },
                    weight:1.8,
             },{
                  x:340,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//28
                    style:{
                      fill:'#7ACDFE',
                    },
                    weight:1,
             },{
                  x:310,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//18
                    style:{
                      fill:'#71B7FD',
                    },
                    weight:0.9,
             },{
                  x:280,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//14
                    style:{
                      fill:'#68A3FD',
                    }, 
                    weight:.72,                 
             },{
                  x:250,
                    y:200,
                    width:12,
                    height:0,
                    fixHeight:5,//9
                    style:{
                      fill:'#608EFC',
                    },
                    weight:0.4,
             }
]

export const circleArr=[
             {
                  x:220,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:190,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:160,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:130,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:520,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:550,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:580,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',
                  }
             },{
                  x:610,
                  y:200,
                  r:6,
                  startAngle:0,
                  endAngle:Math.PI * 2,
                  style:{
                        fill:'#597CFC',

                  }
             }
]
 */